# Generated by extendr: Do not edit by hand

# nolint start

#
# This file was created with the following call:
#   .Call("wrap__make_fiorefactor_wrappers", use_symbols = TRUE, package_name = "fiorefactor")

#' @usage NULL
#' @useDynLib fiorefactor, .registration = TRUE
NULL

Iom <- new.env(parent = emptyenv())

Iom$new <- function(`_name`, intermediate_transactions, total_production) .Call(wrap__Iom__new, `_name`, intermediate_transactions, total_production)

Iom$print <- function() invisible(.Call(wrap__Iom__print, self))

Iom$`_name` <- function() .Call(wrap__Iom___name, self)

Iom$intermediate_transactions <- function() .Call(wrap__Iom__intermediate_transactions, self)

Iom$total_production <- function() .Call(wrap__Iom__total_production, self)

Iom$technical_coefficients_matrix <- function() .Call(wrap__Iom__technical_coefficients_matrix, self)

#' @export
`$.Iom` <- function (self, name) { func <- Iom[[name]]; environment(func) <- environment(); func }

#' @export
`[[.Iom` <- `$.Iom`


# nolint end
