# Generated by extendr: Do not edit by hand

# nolint start

#
# This file was created with the following call:
#   .Call("wrap__make_fiorefactor_wrappers", use_symbols = TRUE, package_name = "fiorefactor")

#' @usage NULL
#' @useDynLib fiorefactor, .registration = TRUE
NULL

#' Rust class for input-output matrix
#' @description
#' This class represents an input-output matrix, which is a representation of the transactions between different sectors of an economy.
#' It contains methods to compute the technical coefficients matrix and other related operations.
#' @usage
#' Iom$new(
#'   name,
#'   intermediate_transactions,
#'   total_production
#' )
#' @format NULL
#' @param name (`character`)\cr
#' A string representing the name of the input-output matrix.
#' @param intermediate_transactions (`matrix`)\cr
#' A matrix of intermediate transactions.
#' @param total_production (`matrix`)\cr A vector of total production.
#' @return A new instance of the `Iom` class.
#' @export
#' @section Methods:
#'\subsection{Method `new`}{
#'Instantiate a new Iom object
#' \subsection{Arguments}{
#'\describe{
#'\item{`name`}{(`character`)\cr A string representing the name of the input-output matrix.}
#'\item{`intermediate_transactions`}{(`matrix`)\cr A matrix of intermediate transactions.}
#'\item{`total_production`}{(`character`)\cr A vector of total production.}
#'}}
#' \subsection{details}
#' This function creates a new instance of the Iom class.
#' \subsection{return}
#' A new instance of the Iom class.
#' \subsection{examples}
#' \preformatted{
#'Iom$new(
#'name = "example",
#'intermediate_transactions = c(1, 2, 3, 4),
#'total_production = c(5, 6)
#')
#'}
#'}
#'
#'\subsection{Method `intermediate_transactions`}{
#'Getter for intermediate_transactions matrix.
#'}
#'
#'\subsection{Method `total_production`}{
#'Getter for total_production matrix.
#'}
#'
#'\subsection{Method `technical_coefficients_matrix`}{
#'Getter for technical_coefficients_matrix.
#'}
#'
#'
#' @section Methods:
#'\subsection{Method `compute_technical_coefficients`}{
#'Compute the technical coefficients matrix and populate the `technical_coefficients_matrix` field.
#' \subsection{usage}
#' \preformatted{
#'Iom$compute_technical_coefficients()
#'}
#' \subsection{details}
#' It computes the technical coefficientex matrix, a nxn matrix, known as `A` matrix, which is the column-wise ratio of intermediate transactions to total production.
#' \subsection{return}
#' Self (invisibly)
#' \subsection{examples}
#' \preformatted{
#'iom <- Iom$new(
#'name = "example",
#'intermediate_transactions = c(1, 2, 3, 4),
#'total_production = c(5, 6)
#')
#'iom$compute_technical_coefficients()
#'iom$technical_coefficients_matrix
#'}
#'}
#'
Iom <- new.env(parent = emptyenv())

Iom$new <- function(name, intermediate_transactions, total_production) .Call(wrap__Iom__new, name, intermediate_transactions, total_production)

Iom$print <- function() invisible(.Call(wrap__Iom__print, self))

Iom$name <- function() .Call(wrap__Iom__name, self)

Iom$intermediate_transactions <- function() .Call(wrap__Iom__intermediate_transactions, self)

Iom$total_production <- function() .Call(wrap__Iom__total_production, self)

Iom$technical_coefficients_matrix <- function() .Call(wrap__Iom__technical_coefficients_matrix, self)

Iom$compute_technical_coefficients <- function() invisible(.Call(wrap__Iom__compute_technical_coefficients, self))

#' @rdname Iom
#' @usage NULL
#' @export
`$.Iom` <- function (self, name) { func <- Iom[[name]]; environment(func) <- environment(); func }

#' @export
`[[.Iom` <- `$.Iom`


# nolint end
